PREFIX nfo: <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#>
PREFIX nie: <http://www.semanticdesktop.org/ontologies/2007/01/19/nie#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX dbpedia: <http://dbpedia.org/ontology/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
INSERT DATA {
    GRAPH <${graph}> {
        <${physicalFile}> a nfo:FileDataObject;
            nie:dataSource <${logicalFile}> ;
            mu:uuid "${phyId}";
            nfo:fileName "${phyFilename}" ;
            dct:creator <http://lblod.data.gift/services/kalliope-api>;
            dct:created "${now}"^^xsd:dateTime;
            dct:modified "${now}"^^xsd:dateTime;
            dct:format "${contentType}";
            nfo:fileSize "${fileSize?string.computer}"^^xsd:integer;
            dbpedia:fileExtension "${fileExtension}".
        <${logicalFile}> a nfo:FileDataObject;
            mu:uuid "${loId}";
            nfo:fileName "${logicalFileName}" ;
            dct:creator <http://lblod.data.gift/services/kalliope-api>;
            dct:created "${now}"^^xsd:dateTime;
            dct:modified "${now}"^^xsd:dateTime;
            dct:format "${contentType}";
            nfo:fileSize "${fileSize?string.computer}"^^xsd:integer;
            dbpedia:fileExtension "${fileExtension}" .
    }
}
